name: "Pull Request Labeler test"
on:
- pull_request_target

jobs:
  labelerTest:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
